repository: arcus-azure/arcus.{Component}
theme: jekyll-theme-slate
logo: https://raw.githubusercontent.com/arcus-azure/arcus/master/media/arcus.png
title: Arcus {Component}
description: {Component} development in Azure with a breeze
plugins:
  - jemoji
